export interface Experience{
    title: string,
    position: string,
    establishmentName: string,  
    timePeriod: string,
}

export interface Link{
  name: string,
  url: string,
}

export interface Skill{
  name: string,
  discription: string,
}

export const fields: string[] = [
    'Computer Science',
    'Information Technology',
    'Telecommunications Engineering',
    'Electrical Engineering',
    'Mechanical Engineering',
    'Civil Engineering',
    'Petroleum Engineering',
    'Chemical Engineering',
    'Industrial Engineering',
    'Business Administration',
    'Economics',
    'Finance',
    'Accounting',
    'Marketing',
    'International Relations',
    'Law',
    'Medicine',
    'Pharmacy',
    'Nursing',
    'Dentistry',
    'Architecture',
    'Urban Planning',
    'Environmental Science',
    'Agricultural Engineering',
    'Agronomy',
    'Veterinary Medicine',
    'Food Science',
    'Nutrition',
    'Geology',
    'Mining Engineering',
    'Geophysics',
    'Physics',
    'Chemistry',
    'Biology',
    'Biochemistry',
    'Microbiology',
    'Pharmaceutical Sciences',
    'Mathematics',
    'Statistics',
    'Applied Mathematics',
    'Computer Engineering',
    'Software Engineering',
    'Data Science',
    'Artificial Intelligence',
    'Machine Learning',
    'Information Systems',
    'Cybersecurity',
    'Network Administration',
    'Telecommunications Management',
    'Electronics',
    'Biotechnology',
    'Genetics',
    'Biomedical Sciences',
    'Medical Laboratory Sciences',
    'Medical Imaging',
    'Radiation Therapy',
    'Physical Therapy',
    'Occupational Therapy',
    'Speech-Language Pathology',
    'Sports Science',
    'Physical Education',
    'Sports Management',
    'Journalism',
    'Mass Communication',
    'Public Relations',
    'Advertising',
    'Media Studies',
    'Graphic Design',
    'Interior Design',
    'Fashion Design',
    'Fine Arts',
    'Performing Arts',
    'Music',
    'Film Studies',
    'Theater',
    'Dance',
    'Photography',
    'Culinary Arts',
    'Hospitality Management',
    'Tourism Management',
    'Event Management',
    'Language Studies',
    'Translation and Interpretation',
    'Education',
    'Psychology',
    'Sociology',
    'Anthropology',
    'Political Science',
    'History',
    'Philosophy',
    'Islamic Studies',
    'Arabic Language and Literature',
    'English Language and Literature',
    'French Language and Literature',
    'Spanish Language and Literature',
    'Linguistics',
    'Library Science',
    'Education Technology',
    'Educational Psychology',
    'Curriculum and Instruction',
    'Educational Leadership',
    'Special Education',
    'Early Childhood Education',
    'Elementary Education',
    'Secondary Education',
    'Physical Education',
    'Educational Administration',
    'Educational Research',
    'Education Policy',
    'Higher Education',
    'Distance Learning',
    'Online Education',
    'E-Learning',
    'Multimedia Education',
    'Adult Education',
    'Vocational Education',
    'Technical Education',
    'Environmental Engineering',
    'Renewable Energy',
    'Water Resources Engineering',
    'Transportation Engineering',
    'Materials Science',
    'Nanotechnology',
    'Robotics',
    'Space Science',
    'Meteorology',
    'Astronomy',
    'Oceanography',
    'Urban Design',
    'Landscape Architecture',
    'Surveying and Geomatics',
    'Construction Management',
    'Quantity Surveying',
    'Project Management',
    'Real Estate',
    'Property Management',
    'International Business',
    'Entrepreneurship',
    'Supply Chain Management',
    'Logistics',
    'Human Resource Management',
    'Organizational Psychology',
    'Conflict Resolution',
    'Counseling Psychology',
    'Clinical Psychology',
    'Forensic Psychology',
    'Social Work',
    'Public Health',
    'Healthcare Administration',
    'Epidemiology',
    'Health Education',
    'Nursing Administration',
    'Medical Informatics',
    'Health Policy',
    'Nutrition and Dietetics',
    'Pharmaceutical Management',
    'Medical Ethics',
    'Health Economics',
    'Healthcare Marketing',
    'Health Law',
    'Health Information Management',
    'Hospital Administration',
    'Nursing Home Administration',
    'Medical Practice Management',
    'Healthcare Entrepreneurship',
    'Mental Health Counseling',
    'Marriage and Family Therapy',
    'Addiction Counseling',
    'School Counseling',
    'Clinical Rehabilitation Counseling',
    'Geriatric Counseling',
    'Vocational Rehabilitation Counseling',
    'Student Affairs',
    'Higher Education Administration',
    'College Counseling',
    'Student Development',
  ];

  export const universitiesAlgeria: string[] = [
    'University of Algiers',
    'Ferhat Abbas Sétif University 1',
    'University of Oran 1 Ahmed Ben Bella',
    'University of Constantine 1',
    'University of Annaba Badji Mokhtar',
    'University of Tlemcen Abou Bekr Belkaid',
    'University of Mostaganem',
    'University of Batna 2 Mustapha Benboulaid',
    'University of Ouargla Kasdi Merbah',
    'University of Blida 1',
    'University of Béjaïa Abderrahmane Mira',
    'University of Batna 1 Hadj Lakhdar',
    'University of Guelma Aymen Sadiki',
    'University of Tizi Ouzou Mouloud Mammeri',
    'University of Skikda',
    'University of Laghouat Amar Telidji',
    'Houari Boumediene University of Sciences and Technology',
    'University of Bechar Kasdi Merbah',
    'University of Chlef Hafiz Boukhalfa',
    'University of Tebessa Larbi Tebessi',
    'University of Djelfa Ziane Achour',
    "M'Hamed Bougara University of Boumerdès",
    'University of El Oued Hamma Lakhdar',
    'University of Mascara',
    'Mentouri Brothers University of Constantine 2',
    'Abdelhamid Ibn Badis University of Mostaganem',
    'University of Tindouf Abdelhafid Boussouf',
    'University of Adrar',
    'Kasdi Merbah University of Ouargla',
    'University of Biskra Mohamed Khider',
    'El Tarf University',
    "Mohamed Boudiaf University of M'Sila",
    'Dr. Yahia Fares University of Médéa',
    'University of El Bayadh',
    'University of Souk Ahras Mohamed Cherif Messaadia',
    'Saad Dahlab University of Blida 2',
    'University of Ghardaia Saad Dahlab',
    'University of Souk Ahras Mohamed Cherif Messaadia',
    'Tahri Mohamed University of Béchar',
    "University of Tissemsilt Larbi Ben M'hidi",
    'Amar Telidji University of Laghouat',
    'University of Bejaia - Targa Ouzemmour',
    'Ferhat Abbas Sétif University 1 - El Bez',
    'Amar Telidji University of Laghouat',
    'Dr. Yahia Fares University of Médéa',
    'Abdelhamid Ibn Badis University of Mostaganem',
    'University of Biskra Mohamed Khider',
    'El Tarf University',
    'Mouloud Mammeri University of Tizi Ouzou',
    'Houari Boumediene University of Sciences and Technology',
  ];
  